dependencies:
  - name: postgresql
    version: 0.8.2-tolerations
    repository: https://barklyprotects.github.io/charts
  - name: redis
    version: 0.8.0
    repository: https://kubernetes-charts.storage.googleapis.com/
