
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-delete-jobs"
  labels:
    app: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": post-delete,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app: {{ template "fullname" . }}
        component: spinnaker
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: kubectl
        hostPath:
          path: /usr/bin/kubectl

      containers:
      - name: post-install-job
        image: "lachlanevenson/k8s-kubectl:v1.6.0"
        volumeMounts:
        - name: kubectl
          mountPath: /kubectl
        command:
        - sh
        - -c
        - "kubectl delete job --namespace {{ .Release.Namespace }} {{.Release.Name}}-db-init {{ if not .Release.IsUpgrade }}{{.Release.Name}}-user-create {{- end }} {{.Release.Name}}-delete-jobs"
