name: prometheus
version: 3.0.0
description: Prometheus is a monitoring system and time series database.
home: https://prometheus.io/
sources:
  - https://github.com/prometheus/alertmanager
  - https://github.com/prometheus/prometheus
  - https://github.com/kubernetes/kube-state-metrics
maintainers:
  - name: Michael Goodness
    email: mgoodness@gmail.com
engine: gotpl
